using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.IO;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraLayout;
using DevExpress.XtraLayout.Helpers;
using DevExpress.Xpo;
using DevExpress.Xpo.DB;
using AirportsRelationsApp.Module.BusinessObjects;

namespace AirportsRelationsAppWinForm.AllForms
{
    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            this.xpInstantFeedbackSource2.ResolveSession += XpInstantFeedbackSource2_ResolveSession;
            // This line of code is generated by Data Source Configuration Wizard
            this.xpInstantFeedbackSource2.DismissSession += XpInstantFeedbackSource2_DismissSession;
        }

        private void BarButtonItem6_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListAirport airForm = new FormListAirport();
            airForm.Show();

        }

        private void BarButtonItem7_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListPlane planeForm = new FormListPlane();
            planeForm.Show();
        }

        private void BarButtonItem8_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListPilot pilotForm = new FormListPilot();
            pilotForm.Show();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_ResolveSession(object sender, ResolveSessionEventArgs e)
        {

            // Assign a session to the Session property,
            e.Session = new DevExpress.Xpo.UnitOfWork();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_DismissSession(object sender, ResolveSessionEventArgs e)
        {

            // Here you can dismiss the session instance you have assigned to the ResolveSessionEventArgs.Session property in the ResolveSession event handler.
            IDisposable session = e.Session as IDisposable;
            if (session != null)
                session.Dispose();
        }
               

        private void BarButtonItem9_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectAiports sA = new SelectAiports();
            sA.Show();
        }

        private void BarButtonItem10_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPilotsFromAirportsA sA = new SelectPilotsFromAirportsA();
            sA.Show();
        }

        private void BarButtonItem11_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPlainInAirportA sA = new SelectPlainInAirportA();
            sA.Show();
        }

        private void BarButtonItem12_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {            
            //using( XPCollection db = new XPCollection() )
            {
                XPCollection db = new XPCollection();
                if (db.Count > 300) return;
                Airport airport1 = new Airport(db.Session);
                airport1.AirportName = "airport1";
                Airport airport2 = new Airport(db.Session);
                airport1.AirportName = "airport2";
                Airport airport3 = new Airport(db.Session);
                airport1.AirportName = "airport3";

                Pilot pilot1 = new Pilot(db.Session);
                pilot1.PilotName = "pilot1";
                Pilot pilot2 = new Pilot(db.Session);
                pilot1.PilotName = "pilot2";
                Pilot pilot3 = new Pilot(db.Session);
                pilot1.PilotName = "pilot3";

                Plane plane1 = new Plane(db.Session);
                plane1.PlaneName = "plane1";
                Plane plane2 = new Plane(db.Session);
                plane1.PlaneName = "plane2";
                Plane plane3 = new Plane(db.Session);
                plane1.PlaneName = "plane3";
                airport1.Pilots.AddRange(new List<Pilot> { pilot1, pilot2, pilot3 });
                airport1.Planes.AddRange(new List<Plane> { plane1, plane2, plane3 });
                plane1.Pilots.AddRange(new List<Pilot> { pilot1, pilot2, pilot3 });
                pilot1.Planes.AddRange(new List<Plane> { plane1, plane2, plane3 });

                db.AddRange(new List<Airport> { airport1, airport2, airport3 });
                db.AddRange(new List<Pilot> { pilot1, pilot2, pilot3 });
                db.AddRange(new List<Plane> { plane1, plane2, plane3 });
            }

            
        }
    }
}