using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using DevExpress.Xpo;
using AirportsRelationsApp.Module.BusinessObjects;
using System.CodeDom.Compiler;
using Microsoft.CSharp;

namespace AirportsRelationsAppWinForm.AllForms
{
    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            this.xpInstantFeedbackSource2.ResolveSession += XpInstantFeedbackSource2_ResolveSession_1;
            // This line of code is generated by Data Source Configuration Wizard
            this.xpInstantFeedbackSource2.DismissSession += XpInstantFeedbackSource2_DismissSession_1;
        }

        private void BarButtonItem6_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListAirport airForm = new FormListAirport();
            airForm.Show();

        }

        private void BarButtonItem7_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListPlane planeForm = new FormListPlane();
            planeForm.Show();
        }

        private void BarButtonItem8_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FormListPilot pilotForm = new FormListPilot();
            pilotForm.Show();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_ResolveSession(object sender, ResolveSessionEventArgs e)
        {

            // Assign a session to the Session property,
            e.Session = new DevExpress.Xpo.UnitOfWork();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_DismissSession(object sender, ResolveSessionEventArgs e)
        {

            // Here you can dismiss the session instance you have assigned to the ResolveSessionEventArgs.Session property in the ResolveSession event handler.
            IDisposable session = e.Session as IDisposable;
            if (session != null)
                session.Dispose();
        }
               

        private void BarButtonItem9_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectAiports sA = new SelectAiports();
            sA.Show();
        }

        private void BarButtonItem10_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPilotsFromAirportsA sA = new SelectPilotsFromAirportsA();
            sA.Show();
        }

        private void BarButtonItem11_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPlainInAirportA sA = new SelectPlainInAirportA();
            sA.Show();
        }

        #region Generate many objects
        private void BarButtonItem12_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (xpCollection1.Count > 300) return;

            Airport airport1 = new Airport(session1); airport1.AirportName = "airport1"; Airport airport2 = new Airport(session1); airport2.AirportName = "airport2"; Airport airport3 = new Airport(session1); airport3.AirportName = "airport3"; Airport airport4 = new Airport(session1); airport4.AirportName = "airport4"; Airport airport5 = new Airport(session1); airport5.AirportName = "airport5"; Airport airport6 = new Airport(session1); airport6.AirportName = "airport6"; Airport airport7 = new Airport(session1); airport7.AirportName = "airport7"; Airport airport8 = new Airport(session1); airport8.AirportName = "airport8"; Airport airport9 = new Airport(session1); airport9.AirportName = "airport9"; Airport airport10 = new Airport(session1); airport10.AirportName = "airport10";
            Airport airport11 = new Airport(session1); airport11.AirportName = "airport11";
            Airport airport12 = new Airport(session1); airport12.AirportName = "airport12";
            Airport airport13 = new Airport(session1); airport13.AirportName = "airport13";
            Airport airport14 = new Airport(session1); airport14.AirportName = "airport14";
            Airport airport15 = new Airport(session1); airport15.AirportName = "airport15";
            Airport airport16 = new Airport(session1); airport16.AirportName = "airport16";
            Airport airport17 = new Airport(session1); airport17.AirportName = "airport17";
            Airport airport18 = new Airport(session1); airport18.AirportName = "airport18";
            Airport airport19 = new Airport(session1); airport19.AirportName = "airport19";
            Airport airport20 = new Airport(session1); airport20.AirportName = "airport20";
            Airport airport21 = new Airport(session1); airport21.AirportName = "airport21";
            Airport airport22 = new Airport(session1); airport22.AirportName = "airport22";
            Airport airport23 = new Airport(session1); airport23.AirportName = "airport23";
            Airport airport24 = new Airport(session1); airport24.AirportName = "airport24";
            Airport airport25 = new Airport(session1); airport25.AirportName = "airport25";
            Airport airport26 = new Airport(session1); airport26.AirportName = "airport26";
            Airport airport27 = new Airport(session1); airport27.AirportName = "airport27";
            Airport airport28 = new Airport(session1); airport28.AirportName = "airport28";
            Airport airport29 = new Airport(session1); airport29.AirportName = "airport29";
            Airport airport30 = new Airport(session1); airport30.AirportName = "airport30";
            Airport airport31 = new Airport(session1); airport31.AirportName = "airport31";
            Airport airport32 = new Airport(session1); airport32.AirportName = "airport32";
            Airport airport33 = new Airport(session1); airport33.AirportName = "airport33";
            Airport airport34 = new Airport(session1); airport34.AirportName = "airport34";
            Airport airport35 = new Airport(session1); airport35.AirportName = "airport35";
            Airport airport36 = new Airport(session1); airport36.AirportName = "airport36";
            Airport airport37 = new Airport(session1); airport37.AirportName = "airport37";
            Airport airport38 = new Airport(session1); airport38.AirportName = "airport38";
            Airport airport39 = new Airport(session1); airport39.AirportName = "airport39";
            Airport airport40 = new Airport(session1); airport40.AirportName = "airport40";
            Airport airport41 = new Airport(session1); airport41.AirportName = "airport41";
            Airport airport42 = new Airport(session1); airport42.AirportName = "airport42";
            Airport airport43 = new Airport(session1); airport43.AirportName = "airport43";
            Airport airport44 = new Airport(session1); airport44.AirportName = "airport44";
            Airport airport45 = new Airport(session1); airport45.AirportName = "airport45";
            Airport airport46 = new Airport(session1); airport46.AirportName = "airport46";
            Airport airport47 = new Airport(session1); airport47.AirportName = "airport47";
            Airport airport48 = new Airport(session1); airport48.AirportName = "airport48";
            Airport airport49 = new Airport(session1); airport49.AirportName = "airport49";
            Airport airport50 = new Airport(session1); airport50.AirportName = "airport50";
            Airport airport51 = new Airport(session1); airport51.AirportName = "airport51";
            Airport airport52 = new Airport(session1); airport52.AirportName = "airport52";
            Airport airport53 = new Airport(session1); airport53.AirportName = "airport53";
            Airport airport54 = new Airport(session1); airport54.AirportName = "airport54";
            Airport airport55 = new Airport(session1); airport55.AirportName = "airport55";
            Airport airport56 = new Airport(session1); airport56.AirportName = "airport56";
            Airport airport57 = new Airport(session1); airport57.AirportName = "airport57";
            Airport airport58 = new Airport(session1); airport58.AirportName = "airport58";
            Airport airport59 = new Airport(session1); airport59.AirportName = "airport59";
            Airport airport60 = new Airport(session1); airport60.AirportName = "airport60";
            Airport airport61 = new Airport(session1); airport61.AirportName = "airport61";
            Airport airport62 = new Airport(session1); airport62.AirportName = "airport62";
            Airport airport63 = new Airport(session1); airport63.AirportName = "airport63";
            Airport airport64 = new Airport(session1); airport64.AirportName = "airport64";
            Airport airport65 = new Airport(session1); airport65.AirportName = "airport65";
            Airport airport66 = new Airport(session1); airport66.AirportName = "airport66";
            Airport airport67 = new Airport(session1); airport67.AirportName = "airport67";
            Airport airport68 = new Airport(session1); airport68.AirportName = "airport68";
            Airport airport69 = new Airport(session1); airport69.AirportName = "airport69";
            Airport airport70 = new Airport(session1); airport70.AirportName = "airport70";
            Airport airport71 = new Airport(session1); airport71.AirportName = "airport71";
            Airport airport72 = new Airport(session1); airport72.AirportName = "airport72";
            Airport airport73 = new Airport(session1); airport73.AirportName = "airport73";
            Airport airport74 = new Airport(session1); airport74.AirportName = "airport74";
            Airport airport75 = new Airport(session1); airport75.AirportName = "airport75";
            Airport airport76 = new Airport(session1); airport76.AirportName = "airport76";
            Airport airport77 = new Airport(session1); airport77.AirportName = "airport77";
            Airport airport78 = new Airport(session1); airport78.AirportName = "airport78";
            Airport airport79 = new Airport(session1); airport79.AirportName = "airport79";
            Airport airport80 = new Airport(session1); airport80.AirportName = "airport80";
            Airport airport81 = new Airport(session1); airport81.AirportName = "airport81";
            Airport airport82 = new Airport(session1); airport82.AirportName = "airport82";
            Airport airport83 = new Airport(session1); airport83.AirportName = "airport83";
            Airport airport84 = new Airport(session1); airport84.AirportName = "airport84";
            Airport airport85 = new Airport(session1); airport85.AirportName = "airport85";
            Airport airport86 = new Airport(session1); airport86.AirportName = "airport86";
            Airport airport87 = new Airport(session1); airport87.AirportName = "airport87";
            Airport airport88 = new Airport(session1); airport88.AirportName = "airport88";
            Airport airport89 = new Airport(session1); airport89.AirportName = "airport89";
            Airport airport90 = new Airport(session1); airport90.AirportName = "airport90";
            Airport airport91 = new Airport(session1); airport91.AirportName = "airport91";
            Airport airport92 = new Airport(session1); airport92.AirportName = "airport92";
            Airport airport93 = new Airport(session1); airport93.AirportName = "airport93";
            Airport airport94 = new Airport(session1); airport94.AirportName = "airport94";
            Airport airport95 = new Airport(session1); airport95.AirportName = "airport95";
            Airport airport96 = new Airport(session1); airport96.AirportName = "airport96";
            Airport airport97 = new Airport(session1); airport97.AirportName = "airport97";
            Airport airport98 = new Airport(session1); airport98.AirportName = "airport98";
            Airport airport99 = new Airport(session1); airport99.AirportName = "airport99";
            Airport airport100 = new Airport(session1); airport100.AirportName = "airport100";
            Pilot pilot1 = new Pilot(session1); pilot1.PilotName = "pilot1";
            Pilot pilot2 = new Pilot(session1); pilot2.PilotName = "pilot2";
            Pilot pilot3 = new Pilot(session1); pilot3.PilotName = "pilot3";
            Pilot pilot4 = new Pilot(session1); pilot4.PilotName = "pilot4";
            Pilot pilot5 = new Pilot(session1); pilot5.PilotName = "pilot5";
            Pilot pilot6 = new Pilot(session1); pilot6.PilotName = "pilot6";
            Pilot pilot7 = new Pilot(session1); pilot7.PilotName = "pilot7";
            Pilot pilot8 = new Pilot(session1); pilot8.PilotName = "pilot8";
            Pilot pilot9 = new Pilot(session1); pilot9.PilotName = "pilot9";
            Pilot pilot10 = new Pilot(session1); pilot10.PilotName = "pilot10";
            Pilot pilot11 = new Pilot(session1); pilot11.PilotName = "pilot11";
            Pilot pilot12 = new Pilot(session1); pilot12.PilotName = "pilot12";
            Pilot pilot13 = new Pilot(session1); pilot13.PilotName = "pilot13";
            Pilot pilot14 = new Pilot(session1); pilot14.PilotName = "pilot14";
            Pilot pilot15 = new Pilot(session1); pilot15.PilotName = "pilot15";
            Pilot pilot16 = new Pilot(session1); pilot16.PilotName = "pilot16";
            Pilot pilot17 = new Pilot(session1); pilot17.PilotName = "pilot17";
            Pilot pilot18 = new Pilot(session1); pilot18.PilotName = "pilot18";
            Pilot pilot19 = new Pilot(session1); pilot19.PilotName = "pilot19";
            Pilot pilot20 = new Pilot(session1); pilot20.PilotName = "pilot20";
            Pilot pilot21 = new Pilot(session1); pilot21.PilotName = "pilot21";
            Pilot pilot22 = new Pilot(session1); pilot22.PilotName = "pilot22";
            Pilot pilot23 = new Pilot(session1); pilot23.PilotName = "pilot23";
            Pilot pilot24 = new Pilot(session1); pilot24.PilotName = "pilot24";
            Pilot pilot25 = new Pilot(session1); pilot25.PilotName = "pilot25";
            Pilot pilot26 = new Pilot(session1); pilot26.PilotName = "pilot26";
            Pilot pilot27 = new Pilot(session1); pilot27.PilotName = "pilot27";
            Pilot pilot28 = new Pilot(session1); pilot28.PilotName = "pilot28";
            Pilot pilot29 = new Pilot(session1); pilot29.PilotName = "pilot29";
            Pilot pilot30 = new Pilot(session1); pilot30.PilotName = "pilot30";
            Pilot pilot31 = new Pilot(session1); pilot31.PilotName = "pilot31";
            Pilot pilot32 = new Pilot(session1); pilot32.PilotName = "pilot32";
            Pilot pilot33 = new Pilot(session1); pilot33.PilotName = "pilot33";
            Pilot pilot34 = new Pilot(session1); pilot34.PilotName = "pilot34";
            Pilot pilot35 = new Pilot(session1); pilot35.PilotName = "pilot35";
            Pilot pilot36 = new Pilot(session1); pilot36.PilotName = "pilot36";
            Pilot pilot37 = new Pilot(session1); pilot37.PilotName = "pilot37";
            Pilot pilot38 = new Pilot(session1); pilot38.PilotName = "pilot38";
            Pilot pilot39 = new Pilot(session1); pilot39.PilotName = "pilot39";
            Pilot pilot40 = new Pilot(session1); pilot40.PilotName = "pilot40";
            Pilot pilot41 = new Pilot(session1); pilot41.PilotName = "pilot41";
            Pilot pilot42 = new Pilot(session1); pilot42.PilotName = "pilot42";
            Pilot pilot43 = new Pilot(session1); pilot43.PilotName = "pilot43";
            Pilot pilot44 = new Pilot(session1); pilot44.PilotName = "pilot44";
            Pilot pilot45 = new Pilot(session1); pilot45.PilotName = "pilot45";
            Pilot pilot46 = new Pilot(session1); pilot46.PilotName = "pilot46";
            Pilot pilot47 = new Pilot(session1); pilot47.PilotName = "pilot47";
            Pilot pilot48 = new Pilot(session1); pilot48.PilotName = "pilot48";
            Pilot pilot49 = new Pilot(session1); pilot49.PilotName = "pilot49";
            Pilot pilot50 = new Pilot(session1); pilot50.PilotName = "pilot50";
            Pilot pilot51 = new Pilot(session1); pilot51.PilotName = "pilot51";
            Pilot pilot52 = new Pilot(session1); pilot52.PilotName = "pilot52";
            Pilot pilot53 = new Pilot(session1); pilot53.PilotName = "pilot53";
            Pilot pilot54 = new Pilot(session1); pilot54.PilotName = "pilot54";
            Pilot pilot55 = new Pilot(session1); pilot55.PilotName = "pilot55";
            Pilot pilot56 = new Pilot(session1); pilot56.PilotName = "pilot56";
            Pilot pilot57 = new Pilot(session1); pilot57.PilotName = "pilot57";
            Pilot pilot58 = new Pilot(session1); pilot58.PilotName = "pilot58";
            Pilot pilot59 = new Pilot(session1); pilot59.PilotName = "pilot59";
            Pilot pilot60 = new Pilot(session1); pilot60.PilotName = "pilot60";
            Pilot pilot61 = new Pilot(session1); pilot61.PilotName = "pilot61";
            Pilot pilot62 = new Pilot(session1); pilot62.PilotName = "pilot62";
            Pilot pilot63 = new Pilot(session1); pilot63.PilotName = "pilot63";
            Pilot pilot64 = new Pilot(session1); pilot64.PilotName = "pilot64";
            Pilot pilot65 = new Pilot(session1); pilot65.PilotName = "pilot65";
            Pilot pilot66 = new Pilot(session1); pilot66.PilotName = "pilot66";
            Pilot pilot67 = new Pilot(session1); pilot67.PilotName = "pilot67";
            Pilot pilot68 = new Pilot(session1); pilot68.PilotName = "pilot68";
            Pilot pilot69 = new Pilot(session1); pilot69.PilotName = "pilot69";
            Pilot pilot70 = new Pilot(session1); pilot70.PilotName = "pilot70";
            Pilot pilot71 = new Pilot(session1); pilot71.PilotName = "pilot71";
            Pilot pilot72 = new Pilot(session1); pilot72.PilotName = "pilot72";
            Pilot pilot73 = new Pilot(session1); pilot73.PilotName = "pilot73";
            Pilot pilot74 = new Pilot(session1); pilot74.PilotName = "pilot74";
            Pilot pilot75 = new Pilot(session1); pilot75.PilotName = "pilot75";
            Pilot pilot76 = new Pilot(session1); pilot76.PilotName = "pilot76";
            Pilot pilot77 = new Pilot(session1); pilot77.PilotName = "pilot77";
            Pilot pilot78 = new Pilot(session1); pilot78.PilotName = "pilot78";
            Pilot pilot79 = new Pilot(session1); pilot79.PilotName = "pilot79";
            Pilot pilot80 = new Pilot(session1); pilot80.PilotName = "pilot80";
            Pilot pilot81 = new Pilot(session1); pilot81.PilotName = "pilot81";
            Pilot pilot82 = new Pilot(session1); pilot82.PilotName = "pilot82";
            Pilot pilot83 = new Pilot(session1); pilot83.PilotName = "pilot83";
            Pilot pilot84 = new Pilot(session1); pilot84.PilotName = "pilot84";
            Pilot pilot85 = new Pilot(session1); pilot85.PilotName = "pilot85";
            Pilot pilot86 = new Pilot(session1); pilot86.PilotName = "pilot86";
            Pilot pilot87 = new Pilot(session1); pilot87.PilotName = "pilot87";
            Pilot pilot88 = new Pilot(session1); pilot88.PilotName = "pilot88";
            Pilot pilot89 = new Pilot(session1); pilot89.PilotName = "pilot89";
            Pilot pilot90 = new Pilot(session1); pilot90.PilotName = "pilot90";
            Pilot pilot91 = new Pilot(session1); pilot91.PilotName = "pilot91";
            Pilot pilot92 = new Pilot(session1); pilot92.PilotName = "pilot92";
            Pilot pilot93 = new Pilot(session1); pilot93.PilotName = "pilot93";
            Pilot pilot94 = new Pilot(session1); pilot94.PilotName = "pilot94";
            Pilot pilot95 = new Pilot(session1); pilot95.PilotName = "pilot95";
            Pilot pilot96 = new Pilot(session1); pilot96.PilotName = "pilot96";
            Pilot pilot97 = new Pilot(session1); pilot97.PilotName = "pilot97";
            Pilot pilot98 = new Pilot(session1); pilot98.PilotName = "pilot98";
            Pilot pilot99 = new Pilot(session1); pilot99.PilotName = "pilot99";
            Pilot pilot100 = new Pilot(session1); pilot100.PilotName = "pilot100";
            Pilot pilot101 = new Pilot(session1); pilot101.PilotName = "pilot101";
            Pilot pilot102 = new Pilot(session1); pilot102.PilotName = "pilot102";
            Pilot pilot103 = new Pilot(session1); pilot103.PilotName = "pilot103";
            Pilot pilot104 = new Pilot(session1); pilot104.PilotName = "pilot104";
            Pilot pilot105 = new Pilot(session1); pilot105.PilotName = "pilot105";
            Pilot pilot106 = new Pilot(session1); pilot106.PilotName = "pilot106";
            Plane plane1 = new Plane(session1); plane1.PlaneName = "plane1";
            Plane plane2 = new Plane(session1); plane2.PlaneName = "plane2";
            Plane plane3 = new Plane(session1); plane3.PlaneName = "plane3";
            Plane plane4 = new Plane(session1); plane4.PlaneName = "plane4";
            Plane plane5 = new Plane(session1); plane5.PlaneName = "plane5";
            Plane plane6 = new Plane(session1); plane6.PlaneName = "plane6";
            Plane plane7 = new Plane(session1); plane7.PlaneName = "plane7";
            Plane plane8 = new Plane(session1); plane8.PlaneName = "plane8";
            Plane plane9 = new Plane(session1); plane9.PlaneName = "plane9";
            Plane plane10 = new Plane(session1); plane10.PlaneName = "plane10";
            Plane plane11 = new Plane(session1); plane11.PlaneName = "plane11";
            Plane plane12 = new Plane(session1); plane12.PlaneName = "plane12";
            Plane plane13 = new Plane(session1); plane13.PlaneName = "plane13";
            Plane plane14 = new Plane(session1); plane14.PlaneName = "plane14";
            Plane plane15 = new Plane(session1); plane15.PlaneName = "plane15";
            Plane plane16 = new Plane(session1); plane16.PlaneName = "plane16";
            Plane plane17 = new Plane(session1); plane17.PlaneName = "plane17";
            Plane plane18 = new Plane(session1); plane18.PlaneName = "plane18";
            Plane plane19 = new Plane(session1); plane19.PlaneName = "plane19";
            Plane plane20 = new Plane(session1); plane20.PlaneName = "plane20";
            Plane plane21 = new Plane(session1); plane21.PlaneName = "plane21";
            Plane plane22 = new Plane(session1); plane22.PlaneName = "plane22";
            Plane plane23 = new Plane(session1); plane23.PlaneName = "plane23";
            Plane plane24 = new Plane(session1); plane24.PlaneName = "plane24";
            Plane plane25 = new Plane(session1); plane25.PlaneName = "plane25";
            Plane plane26 = new Plane(session1); plane26.PlaneName = "plane26";
            Plane plane27 = new Plane(session1); plane27.PlaneName = "plane27";
            Plane plane28 = new Plane(session1); plane28.PlaneName = "plane28";
            Plane plane29 = new Plane(session1); plane29.PlaneName = "plane29";
            Plane plane30 = new Plane(session1); plane30.PlaneName = "plane30";
            Plane plane31 = new Plane(session1); plane31.PlaneName = "plane31";
            Plane plane32 = new Plane(session1); plane32.PlaneName = "plane32";
            Plane plane33 = new Plane(session1); plane33.PlaneName = "plane33";
            Plane plane34 = new Plane(session1); plane34.PlaneName = "plane34";
            Plane plane35 = new Plane(session1); plane35.PlaneName = "plane35";
            Plane plane36 = new Plane(session1); plane36.PlaneName = "plane36";
            Plane plane37 = new Plane(session1); plane37.PlaneName = "plane37";
            Plane plane38 = new Plane(session1); plane38.PlaneName = "plane38";
            Plane plane39 = new Plane(session1); plane39.PlaneName = "plane39";
            Plane plane40 = new Plane(session1); plane40.PlaneName = "plane40";
            Plane plane41 = new Plane(session1); plane41.PlaneName = "plane41";
            Plane plane42 = new Plane(session1); plane42.PlaneName = "plane42";
            Plane plane43 = new Plane(session1); plane43.PlaneName = "plane43";
            Plane plane44 = new Plane(session1); plane44.PlaneName = "plane44";
            Plane plane45 = new Plane(session1); plane45.PlaneName = "plane45";
            Plane plane46 = new Plane(session1); plane46.PlaneName = "plane46";
            Plane plane47 = new Plane(session1); plane47.PlaneName = "plane47";
            Plane plane48 = new Plane(session1); plane48.PlaneName = "plane48";
            Plane plane49 = new Plane(session1); plane49.PlaneName = "plane49";
            Plane plane50 = new Plane(session1); plane50.PlaneName = "plane50";
            Plane plane51 = new Plane(session1); plane51.PlaneName = "plane51";
            Plane plane52 = new Plane(session1); plane52.PlaneName = "plane52";
            Plane plane53 = new Plane(session1); plane53.PlaneName = "plane53";
            Plane plane54 = new Plane(session1); plane54.PlaneName = "plane54";
            Plane plane55 = new Plane(session1); plane55.PlaneName = "plane55";
            Plane plane56 = new Plane(session1); plane56.PlaneName = "plane56";
            Plane plane57 = new Plane(session1); plane57.PlaneName = "plane57";
            Plane plane58 = new Plane(session1); plane58.PlaneName = "plane58";
            Plane plane59 = new Plane(session1); plane59.PlaneName = "plane59";
            Plane plane60 = new Plane(session1); plane60.PlaneName = "plane60";
            Plane plane61 = new Plane(session1); plane61.PlaneName = "plane61";
            Plane plane62 = new Plane(session1); plane62.PlaneName = "plane62";
            Plane plane63 = new Plane(session1); plane63.PlaneName = "plane63";
            Plane plane64 = new Plane(session1); plane64.PlaneName = "plane64";
            Plane plane65 = new Plane(session1); plane65.PlaneName = "plane65";
            Plane plane66 = new Plane(session1); plane66.PlaneName = "plane66";
            Plane plane67 = new Plane(session1); plane67.PlaneName = "plane67";
            Plane plane68 = new Plane(session1); plane68.PlaneName = "plane68";
            Plane plane69 = new Plane(session1); plane69.PlaneName = "plane69";
            Plane plane70 = new Plane(session1); plane70.PlaneName = "plane70";
            Plane plane71 = new Plane(session1); plane71.PlaneName = "plane71";
            Plane plane72 = new Plane(session1); plane72.PlaneName = "plane72";
            Plane plane73 = new Plane(session1); plane73.PlaneName = "plane73";
            Plane plane74 = new Plane(session1); plane74.PlaneName = "plane74";
            Plane plane75 = new Plane(session1); plane75.PlaneName = "plane75";
            Plane plane76 = new Plane(session1); plane76.PlaneName = "plane76";
            Plane plane77 = new Plane(session1); plane77.PlaneName = "plane77";
            Plane plane78 = new Plane(session1); plane78.PlaneName = "plane78";
            Plane plane79 = new Plane(session1); plane79.PlaneName = "plane79";
            Plane plane80 = new Plane(session1); plane80.PlaneName = "plane80";
            Plane plane81 = new Plane(session1); plane81.PlaneName = "plane81";
            Plane plane82 = new Plane(session1); plane82.PlaneName = "plane82";
            Plane plane83 = new Plane(session1); plane83.PlaneName = "plane83";
            Plane plane84 = new Plane(session1); plane84.PlaneName = "plane84";
            Plane plane85 = new Plane(session1); plane85.PlaneName = "plane85";
            Plane plane86 = new Plane(session1); plane86.PlaneName = "plane86";
            Plane plane87 = new Plane(session1); plane87.PlaneName = "plane87";
            Plane plane88 = new Plane(session1); plane88.PlaneName = "plane88";
            Plane plane89 = new Plane(session1); plane89.PlaneName = "plane89";
            Plane plane90 = new Plane(session1); plane90.PlaneName = "plane90";
            Plane plane91 = new Plane(session1); plane91.PlaneName = "plane91";
            Plane plane92 = new Plane(session1); plane92.PlaneName = "plane92";
            Plane plane93 = new Plane(session1); plane93.PlaneName = "plane93";
            Plane plane94 = new Plane(session1); plane94.PlaneName = "plane94";
            Plane plane95 = new Plane(session1); plane95.PlaneName = "plane95";
            Plane plane96 = new Plane(session1); plane96.PlaneName = "plane96";
            Plane plane97 = new Plane(session1); plane97.PlaneName = "plane97";
            Plane plane98 = new Plane(session1); plane98.PlaneName = "plane98";
            Plane plane99 = new Plane(session1); plane99.PlaneName = "plane99";
            Plane plane100 = new Plane(session1); plane100.PlaneName = "plane100";
            Plane plane101 = new Plane(session1); plane101.PlaneName = "samplane101";
            Plane plane102 = new Plane(session1); plane102.PlaneName = "samplane102";
            Plane plane103 = new Plane(session1); plane103.PlaneName = "samplane103";
            Plane plane104 = new Plane(session1); plane104.PlaneName = "samplane104";
            Plane plane105 = new Plane(session1); plane105.PlaneName = "samplane105";
            Plane plane106 = new Plane(session1); plane106.PlaneName = "samplane106";

            airport1.Pilots.AddRange(new List<Pilot> { pilot1, pilot2, pilot38, pilot17 });
            airport5.Pilots.AddRange(new List<Pilot> { pilot10, pilot17, pilot18, pilot20, pilot30 });
            airport15.Pilots.AddRange(new List<Pilot> { pilot10, pilot27, pilot18, pilot50, pilot32 });
            airport55.Pilots.AddRange(new List<Pilot> { pilot10, pilot17, pilot38, pilot20, pilot30 });

            airport1.Planes.AddRange(new List<Plane> { plane1, plane12, plane23, plane38, plane42, plane15, plane100 });
            airport12.Planes.AddRange(new List<Plane> { plane3, plane15, plane1, plane33, plane42, plane15, plane100 });
            airport78.Planes.AddRange(new List<Plane> { plane2, plane13, plane18, plane38, plane42, plane70, plane100 });
            airport35.Planes.AddRange(new List<Plane> { plane1, plane1, plane27, plane8, plane42, plane60, plane100 });

            plane1.Pilots.AddRange(new List<Pilot> { pilot8, pilot11, pilot20, pilot35, pilot42, pilot52, pilot54, pilot63, pilot88, pilot85, pilot100 });
            plane8.Pilots.AddRange(new List<Pilot> { pilot5, pilot19, pilot10, pilot45, pilot32, pilot52, pilot54, pilot73, pilot89, pilot100 });
            plane88.Pilots.AddRange(new List<Pilot> { pilot2, pilot13, pilot11, pilot40, pilot38, pilot58, pilot52, pilot73, pilot79, pilot99 });
            plane101.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });
            plane102.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });
            plane103.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });
            plane104.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });
            plane105.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });
            plane106.Pilots.AddRange(new List<Pilot> { pilot101, pilot102, pilot100 });

            pilot42.Planes.AddRange(new List<Plane> { plane3, plane53, plane13, plane8, plane7, plane10, plane9, plane37, plane49, plane52, plane87, plane92, plane93 });
            pilot32.Planes.AddRange(new List<Plane> { plane3, plane5, plane11, plane8, plane9, plane10, plane19, plane37, plane40, plane53, plane87, plane92, plane93 });
            pilot19.Planes.AddRange(new List<Plane> { plane8, plane53, plane19, plane8, plane88, plane10, plane9, plane37, plane43, plane51, plane87, plane90, plane83 });
            pilot101.Planes.AddRange(new List<Plane> { plane101, plane102, plane103 });
            pilot102.Planes.AddRange(new List<Plane> { plane104, plane106, plane103 });
            pilot103.Planes.AddRange(new List<Plane> { plane104, plane106, plane103 });
            pilot104.Planes.AddRange(new List<Plane> { plane104, plane106, plane103 });
            session1.Save(new List<Airport> { airport1, airport2, airport3, airport4, airport5, airport6, airport7, airport8, airport9, airport10, airport11, airport12, airport13, airport14, airport15, airport16, airport17, airport18, airport19, airport20, airport21, airport22, airport23, airport24, airport25, airport26, airport27, airport28, airport29, airport30, airport31, airport32, airport33, airport34, airport35, airport36, airport37, airport38, airport39, airport40, airport41, airport42, airport43, airport44, airport45, airport46, airport47, airport48, airport49, airport50, airport51, airport52, airport53, airport54, airport55, airport56, airport57, airport58, airport59, airport60, airport61, airport62, airport63, airport64, airport65, airport66, airport67, airport68, airport69, airport70, airport71, airport72, airport73, airport74, airport75, airport76, airport77, airport78, airport79, airport80, airport81, airport82, airport83, airport84, airport85, airport86, airport87, airport88, airport89, airport90, airport91, airport92, airport93, airport94, airport95, airport96, airport97, airport98, airport99, airport100 });
            session1.Save(new List<Plane> { plane1, plane2, plane3, plane4, plane5, plane6, plane7, plane8, plane9, plane10, plane11, plane12, plane13, plane14, plane15, plane16, plane17, plane18, plane19, plane20, plane21, plane22, plane23, plane24, plane25, plane26, plane27, plane28, plane29, plane30, plane31, plane32, plane33, plane34, plane35, plane36, plane37, plane38, plane39, plane40, plane41, plane42, plane43, plane44, plane45, plane46, plane47, plane48, plane49, plane50, plane51, plane52, plane53, plane54, plane55, plane56, plane57, plane58, plane59, plane60, plane61, plane62, plane63, plane64, plane65, plane66, plane67, plane68, plane69, plane70, plane71, plane72, plane73, plane74, plane75, plane76, plane77, plane78, plane79, plane80, plane81, plane82, plane83, plane84, plane85, plane86, plane87, plane88, plane89, plane90, plane91, plane92, plane93, plane94, plane95, plane96, plane97, plane98, plane99, plane100, plane101, plane102, plane103, plane104, plane105, plane106 });
            session1.Save(new List<Pilot> { pilot1, pilot2, pilot3, pilot4, pilot5, pilot6, pilot7, pilot8, pilot9, pilot10, pilot11, pilot12, pilot13, pilot14, pilot15, pilot16, pilot17, pilot18, pilot19, pilot20, pilot21, pilot22, pilot23, pilot24, pilot25, pilot26, pilot27, pilot28, pilot29, pilot30, pilot31, pilot32, pilot33, pilot34, pilot35, pilot36, pilot37, pilot38, pilot39, pilot40, pilot41, pilot42, pilot43, pilot44, pilot45, pilot46, pilot47, pilot48, pilot49, pilot50, pilot51, pilot52, pilot53, pilot54, pilot55, pilot56, pilot57, pilot58, pilot59, pilot60, pilot61, pilot62, pilot63, pilot64, pilot65, pilot66, pilot67, pilot68, pilot69, pilot70, pilot71, pilot72, pilot73, pilot74, pilot75, pilot76, pilot77, pilot78, pilot79, pilot80, pilot81, pilot82, pilot83, pilot84, pilot85, pilot86, pilot87, pilot88, pilot89, pilot90, pilot91, pilot92, pilot93, pilot94, pilot95, pilot96, pilot97, pilot98, pilot99, pilot100, pilot101, pilot102, pilot103, pilot104, pilot105, pilot106 });
        }

            #endregion

            private List<string> GenerateCode()
        {
            var listString = new List<string>();
            listString.Add("if (xpCollection1.Count > 300) return;\n");
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"Airport airport{i} = new Airport(session1); airport{i}.AirportName = \"airport{i}\";");
            }
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"Pilot pilot{i} = new Pilot(session1); pilot{i}.PilotName = \"pilot{i}\";");
            }
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"Plane plane{i} = new Plane(session1); plane{i}.PlaneName = \"plane{i}\";");
            }
            listString.Add("session1.Save(new List<Airport> {");
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"airport{i}, ");
            }
            listString.Add("}");
            listString.Add("session1.Save(new List<Pilot> {");
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"pilot{i}, ");
            }
            listString.Add("}");
            listString.Add("session1.Save(new List<Plane> {");
            for (int i = 1; i <= 100; i++)
            {
                listString.Add($"plane{i}, ");
            }
            listString.Add("}");
            return listString;
        }

        private void BarButtonItem13_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPilotWIthP spp = new SelectPilotWIthP();
            spp.Show();
            
        }

        private void BarButtonItem14_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectPilotFromPlaneS ssp = new SelectPilotFromPlaneS();
            ssp.Show();
        }

        private void BarButtonItem15_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            SelectAiportsWithCountPlaneMoreThenTen sat = new SelectAiportsWithCountPlaneMoreThenTen();
            sat.Show();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_ResolveSession_1(object sender, ResolveSessionEventArgs e)
        {

            // Assign a session to the Session property,
            e.Session = new DevExpress.Xpo.UnitOfWork();
        }

        // This event is generated by Data Source Configuration Wizard
        void XpInstantFeedbackSource2_DismissSession_1(object sender, ResolveSessionEventArgs e)
        {

            // Here you can dismiss the session instance you have assigned to the ResolveSessionEventArgs.Session property in the ResolveSession event handler.
            IDisposable session = e.Session as IDisposable;
            if (session != null)
                session.Dispose();
        }

        private void BarButtonItem16_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Form1 f = new Form1();
            f.Show();
        }
    }    
}