using DevExpress.Xpo.DB;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AirportsRelationsAppWinForm.AllForms
{
    public partial class SelectAiports : Form
    {
        public SelectAiports()
        {
            InitializeComponent();
            var db = GetAirportSimpleData();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void SelectAiports_Load(object sender, EventArgs e)
        {
            
        }

        public SelectedData GetAirportSimpleData()
        {
            return xpCollection1.Session.ExecuteQuery(queryString);
        }

        static string queryString = "SELECT [AirportName] AS Airport FROM [AirportsRelationsWF].[dbo].[Airport]";
    }
}

